import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import LenisProvider from "./providers/LenisProvider";
import Footer from "./components/Footer";
import { StaggeredMenu } from "./components/StaggeredMenu";
import ClientWrapper from "./ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  { label: "Home", ariaLabel: "Go to Home", link: "/" },
  { label: "About", ariaLabel: "Go to About section", link: "/#about" },
  { label: "Events", ariaLabel: "Go to Events", link: "/events" },
  { label: "Team", ariaLabel: "Go to Team", link: "/team" },
  { label: "Register", ariaLabel: "Go to Registration", link: "/join-us" },
];

const socialItems = [
  { label: "Instagram", link: "https://instagram.com" },
  { label: "LinkedIn", link: "https://linkedin.com" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <Navbar />
        {/* StaggeredMenu only visible on mobile (screens < md) */}
        <div className="md:hidden">
          <StaggeredMenu
            items={menuItems}
            socialItems={socialItems}
            isFixed={true}
            position="right"
            colors={["#1e1e22", "#3b82f6"]}
            accentColor="#3b82f6"
            displaySocials={true}
            displayItemNumbering={true}
          />
        </div>
        <LenisProvider>
          <ClientWrapper> {children}</ClientWrapper>
        </LenisProvider>
        {<Footer />}
      </body>
    </html>
  );
}

